### PR TITLE
Updated ksml.lua

### PR DESCRIPTION
**Pull request by bauen1**
Added color tags lookup table.

### CODE REVIEW

**Comment by Lemmmy** [comment]
much better :+1:

**Comment by Lemmmy** [comment]
WAIT HANG ON WHAT

**Comment by Lustyn** [comment]
Not quite the need to merge this, but I guess its up to Taras anyways? Just a minor fix and Taras has his ways of programming things.

**Comment by Lemmmy** [comment]
no this is a lot cl eaner justyn is gay

**Comment by Lustyn** [comment]
@Lemmmy blame @BTCTaras for that tag

**Comment by Lemmmy** [comment]
i already have

**Comment by bauen1** [comment]
Kristscape needs a BlameBTCTaras tag for that lol.

**Comment by Lemmmy** [comment]
#blametaras

**Comment by BTCTaras** [comment]
Woah, thanks! I love PRs :)

I forgot to upload the latest changes I've made, but this will be easy to merge anyways

I will update the repo when I get home

**Comment by Lemmmy** [comment]
taras look at skype you centipede

**Comment by BTCTaras** [comment]
i'm at work and far away from my computer

**Comment by Lemmmy** [comment]
well then grow your arms out so you can reach your computer

**Comment by BTCTaras** [comment]
i am _really_ far away

**Comment by Lemmmy** [comment]
you can do anything if you believe! :rainbow: :sparkles:

**Comment by Lustyn** [comment]
@BTCTaras Its 1pm, time to wake up!

**Comment by BTCTaras** [comment]
i'm not asleep you clods!!

**Comment by Lemmmy** [comment]
sneak peak of secret project!!!!!!!!!!!!

**Comment by Lustyn** [comment]
But I thought your job was to slave over the computer everyday working for the demanding ComputerCraft community?!?!

**Comment by Lemmmy** [comment]
no that's mine **cough**

**Comment by BTCTaras** [comment]
ya justyn i outsourced to lemmmy

**Comment by Lemmmy** [comment]
yeah im having like death problems because of all this work

**Comment by BTCTaras** [comment]
also the lack of post requests is one of those things that danny wanted to implement if he got to host the node

**Comment by Lemmmy** [comment]
all new API submission calls are `POST`, old are obviously `GET`

**Comment by BTCTaras** [comment]
can we talk about this in the comments of some commit somewhere instead of this completely unrelated PR

**Comment by Lustyn** [comment]
This just in: Lemmmy and Taras spoil the secret project

**Comment by Lemmmy** [comment]
fuck

**Comment by BTCTaras** [comment]
god damn it

**Comment by Lemmmy** [comment]
@BTCTaras get the slack app

**Comment by BTCTaras** [comment]
for a phone? i don't have mine with me

**Comment by Lemmmy** [comment]
can you acccess slack on whatever workstation you're on right now

**Comment by BTCTaras** [comment]
if it's a web app then sure

**Comment by BTCTaras** [comment]
alternatively we could start a tradition of moving our everyday conversations to the comment section of recently merged kristscape pull requests

**Comment by Lemmmy** [comment]
yeah its just http://(team name).slack.com

**Comment by Lemmmy** [comment]
omg that would be amazing

**Comment by BTCTaras** [comment]
lemmmy can you make a pull request that changes `LEMMYSSOUL` to `LEMMMYSSOUL` so that we can spam that instead of this

**Comment by Lemmmy** [comment]
yeah ofc

**Comment by BTCTaras** [comment]
:100:

**Comment by bauen1** [comment]
So back on topic, i would suggest a blamtaras tag 😄

**Comment by BTCTaras** [comment]
Maybe a `[BLAME3D6]` tag? What would it do

**Comment by bauen1** [comment]
Dunno, maybe a script displaying a blue screen of death and saying blame 3d6 or something like that?

**Comment by Lemmmy** [comment]
it would have http://kristtest.lemmmy.pw/down.html ksml edition

**Comment by Lemmmy** [comment]
and if note blocks are connected it does the song

**Comment by bauen1** [comment]
That would certainly do the job.

**Comment by BTCTaras** [comment]
Lemmmy you are satan

**Comment by Lemmmy** [comment]
i am shitpost lord

**Comment by Lemmmy** [comment]
i might register for a shitload of forums and then PM the admins with a really long and formal message asking for my own title, 'Shitpost Lord'

**Comment by BTCTaras** [comment]
That would be one of the strangest conspiracies you've ever been a part of

**Comment by BTCTaras** [comment]
And you have been in like twelve in the last two months

**Comment by Lemmmy** [comment]
holy shit i never actually looked at `ksml.lua`
 how long did you guys wait for me to read this file?

**Comment by BTCTaras** [comment]
uhhhhh that's not in the latest

**Comment by bauen1** [comment]
about a day according to the commits

**Pull request merged**
