### PR TITLE
Make kristscape great again

### PR DESCRIPTION
**Pull request by Lignum**
Cleaned up the code a lot. It's still not entirely conformant to CONVENTIONS.md (variable names in particular), but it's much better than before. I also added a gitignore file to make working with the code easier.

### CODE REVIEW

**Comment by Lemmmy** [comment]
i literally want to kill myself

**Comment by Lustyn** [comment]
Lignum Trump

**Comment by Lemmmy** [comment]
donald strunz

**Comment by Lignum** [comment]
yes

**Comment by Lignum** [comment]
merge pls

**Comment by Lemmmy** [comment]
do you reckon i'd get funny looks if i went to the town and bought a rope

**Comment by Lemmmy** [comment]
i surveyed my house there's nowhere i can hang ar ope from what do you reckon the odds are of becoming a vegetable if you jump in front of a car

**Comment by Lemmmy** [comment]
like i dont want to become a pralaiysed when i do it iu just want to be dead asnd ismple easy fix

**Comment by Lignum** [comment]
Uh this is a browser for a cryptocurrency

**Pull request merged**
