### PR TITLE
Rename kristscape to kristscape.lua

### PR DESCRIPTION
**Pull request by AshtonSnapp**
This is so syntax is highlighted correctly.

### CODE REVIEW

**Comment by bauen1** [comment]
Hm while i like having a .lua on lua files, computer craft programs mostly don't have them, so having a .lua in the repo but making a installer remove it?

**Comment by BTCTaras** [comment]
I decided against the extension because `kristscape` is the file that is meant to be ran as a program. `.gitattributes` already considers `kristscape` to be a Lua file anyways.

**Comment by Lustyn** [comment]
most text editors have a language tab for a reason

**Comment by Luca0208** [comment]
@BTCTaras This confuses me every time, could you close this please

**Pull request closed without merging**
