### PR TITLE
Fixed a major typo

### PR DESCRIPTION
**Pull request by Lemmmy**

### CODE REVIEW

**Comment by BTCTaras** [comment]
You have literally saved the entire project

**Comment by Lignum** [comment]
I object that Lemmmy's soul, just like his skin is so extremely white that anything within his proximity is not only blinded but also forcefully blown away by the great amount of light particles being emitted by him. Therefore, this variable is wrong.

**Comment by BTCTaras** [comment]
Well Lignum why don't you make a pull request and fix it :+1:

**Comment by BTCTaras** [comment]
Every time someone opens a pull request for kristscape a kitten gets to eat :rainbow: :rainbow: :sparkles: :sparkling_heart:

**Comment by Lemmmy** [comment]
that sounds unhealthy

**Comment by BTCTaras** [comment]
the kittens are malnourished and dying

**Comment by Lignum** [comment]
@BTCTaras i woudl ybut om too lazy

**Comment by Lemmmy** [comment]
you ok liggy

**Comment by BTCTaras** [comment]
ya lig you sound drunk like you **don't care about the starving kittens**

**Pull request merged**
