### PR TITLE
#8 Make it request the site using https when getting the code 302

### PR DESCRIPTION
**Pull request by Luca0208**
This will fix problems for users that store their site in dropbox. But not if github does shit again like for #8 :/

### CODE REVIEW

**Comment by Lemmmy** [comment]
you do realise 302 means redirect, not "go and use https". it could be redirecting anywhere.

**Comment by dmarcuse** [comment]
It could be redirection from HTTPS to HTTP for all we know.

**Comment by Luca0208** [comment]
Ik that 302 means redirect. But without headers we can only guess that it means go to https://pageyoujusttried, e.g. dropbox does that.

Also it can't be https to http because we are trying http first

**Comment by BTCTaras** [comment]
I think that he means a given 302 was intended to go from HTTPS to HTTP

**Comment by Lemmmy** [comment]
we could make a little proxy that returns the `HEAD` response for a page in plaintext, since CC is too stupid to have one on its own. i can make a demo of this shortly

**Comment by Luca0208** [comment]
And how schould we get an 302 intended from https to http if we request the http version? Redurection from http to https is something many servers do, so I think without headers this is the best guess we can make. That proxy would be even better, because you could handle all redirects.

**Comment by dmarcuse** [comment]
AFAIK CC will never return a handle for any response code other than 200, and will automatically follow 300 redirects. You can test this with [this site](http://httpstat.us/) if you like.

**Comment by BTCTaras** [comment]
302 seems to work as intended in CC, but I'm not sure making it automatically try HTTPS is the best plan here. I think we should do that elsewhere.

**Comment by WillowMauldin** [comment]
Perhaps that could be included somewhere in Krist's "DNS" system?

**Comment by Lemmmy** [comment]
yeah tahts what i was thinking, just a simple proxy that returns the http response (headers and response code included) in the body or something

**Comment by Luca0208** [comment]
I definitely think the proxy is a lot better than this PR. If you have the same opinion please close this down

**Comment by BTCTaras** [comment]
I think so too. We'll settle it in the Krist server instead of here

**Pull request closed without merging**
