### PR TITLE
Make it request the site using https when getting the code 302

### PR DESCRIPTION
**Pull request by Luca0208**
This will fix problems for users that use dropbox.

### CODE REVIEW

**Comment by bauen1** [comment]
Hm, great so far, but it might not be a good idea to show the user their using https when their only connected using http

**Comment by Luca0208** [comment]
What? It only starts an https request on an Error 302

**Comment by bauen1** [comment]
On line 259 in kristscape you load the page using **http** but set the title bars header to **https**

**Comment by Luca0208** [comment]
oh did I place the set setstatus() in the wrong place? Lemme fix

**Comment by Luca0208** [comment]
Wait now I am confused. None of my commits is on GitHub anymore. I'll need to create a new PR for this.

**Comment by bauen1** [comment]
The changes are still in there, you can click on them and view them
Wait, let me think about this again.

**Comment by Luca0208** [comment]
This is strange. I have all the changes on my mac. In about 2-3 hours I will open a new PR with all the changes there.

**Pull request closed without merging**
