### PR TITLE
Stop using load for a lookup table

### PR DESCRIPTION
**Pull request by dmarcuse**
seriously who thought using `load` would be a good idea

### CODE REVIEW

**Comment by dmarcuse** [comment]
also it works for either numeric or string keys now

**Comment by dmarcuse** [comment]
why did you make a lookup table for this anyways why not just use `string.char`

**Comment by Luca0208** [comment]
The lookup table is so that you can just use lookup[stuff] with strings AND the number indexes.

**Comment by dmarcuse** [comment]
well i fixed it

**Comment by Luca0208** [comment]
I think what you have is a really good solution 👍

**Comment by dmarcuse** [comment]
just checked the git blame, I wouldn't expect anyone but @BTCTaras to use `load` instead of `string.char` and I guessed right

**Comment by BTCTaras** [comment]
haha ha

**Comment by BTCTaras** [comment]
uhh

**Comment by BTCTaras** [comment]
ha

**Comment by bauen1** [comment]
Hum what does the Revert button do ?

**Comment by dmarcuse** [comment]
dont even dare @bauen1 you're partially responsible for this mess too you know

**Comment by bauen1** [comment]
Uhm i left the load there because i though it had a reason to be there

**Comment by BTCTaras** [comment]
it was a temporary solution to a temporary problem and i accept full responsibility

**Comment by dmarcuse** [comment]
i'll fix the other lookup tables eventually too

**Comment by Luca0208** [comment]
Why can everyone press revert. I don't have write access why am I able to (in theory) revert it.

**Comment by BTCTaras** [comment]
that would create a fork where it is reverted iirc

**Comment by dmarcuse** [comment]
am i the only one that DOESNT have access to the revert button?

**Comment by bauen1** [comment]
XD

**Comment by BTCTaras** [comment]
yes because you own the pr

**Comment by Luca0208** [comment]
Probably because you already have a version

**Comment by dmarcuse** [comment]
later i'll make a proper metatable powered color lookup table

**Comment by Luca0208** [comment]
actually it's not because he owns the PR

i can revert

**Comment by Luca0208** [comment]
That's the SCRIPT PR and I can revert

**Pull request merged**
